a = input('Digite algo pelo teclado: ')
print('O tipo primitivo desse valor é:', type(a))
print('É alfabético?', a.isalpha())
print('É Numérico?', a.isnumeric())
print('É alfanumérico?', a.isalnum())
print('Está tudo escrito em minúsculo?', a.isupper())
print('Está tudo escrito em minúsculo?', a.islower())
print('É um número decimal?', a.isdecimal())
print('É um identificador?', a.isidentifier())
print('Pode ser impresso?', a.isprintable())
print('Começa com letras maiúsculas e termina com minúsculas?', a.istitle())
print('É um dígito?', a.isdigit())
print('Contém apenas espaços?', a.isspace())
